services:
  web:
    container_name: scrap_py
    build:
      context: ..
      dockerfile: docker-config/Dockerfile
    environment:
      # PODE ser prod ou dev, por default assume prod
      - TIPO_AMBIENTE=dev
      - PORT=5000
      - FLASK_ENV=development
      - FIREBASE_USE_REAL=false
      - FIREBASE_PROJECT_ID=mega-sena-40cff
    volumes:
      - ..:/home/user
    working_dir: /home/user
    #command: 'npm run build'
    restart: on-failure
    ports:
      - 5001:5000